### ISSUE TITLE
Reconciliation of Work records as opposed to Authorities

### ISSUE THREAD

**Issue by shlomosanders** [LD4P/ld4-community-recon#41]
## Primary Actor (Required if possible)

A cataloger and/or automatic processing

## Scope (Optional)

My institution, my regional consortium, etc.

## Story (Required)

Since most Work URIs (and records) will be created at the institution level the issue of knowing that 2 Work records are the actually the same across 2 or more institutions becomes an issue if the basis for "sameness" is the URI of the Work record. The same can be said for BIBFRAME Instances. Many of the other use cases described by others that are for Authorities apply here too (i.e. manual handling of exceptions).

**Comment by osma** [comment]
This is also potentially a problem within a single institution. E.g. after converting a catalog of MARC bibliographic records to BIBFRAME using the marc2bibframe2 converter, there are many duplicate Works within the output RDF, because the conversion tool doesn't even try to extract Works from the collection. For that, a work clustering/extraction method such as the OCLC "FRBR Work-Set Algorithm" can be used, but there are lots of implementation details to consider and the result is likely to be far from perfect.

**Comment by vcharles89** [comment]
This use case may be similar to #51

**Comment by shlomosanders** [comment]
Indeed the same.
Not that reconciling Works just based on the Title is not enough.

**Comment by remerjohnson** [comment]
Just as a general complaint, I don't see why one institution couldn't take it upon themselves to make a Work authorities source, much like VIAF. Hundreds of institutions minting Works for the same things seems to violate the overall purpose here...
