### ISSUE TITLE
Write up email + first pass of emailing out call for use cases

### ISSUE THREAD

**Issue by cmharlow** [LD4P/ld4-community-recon#43]
Want public call for requesting reconciliation + entity resolution use cases. Need to write up email + list of communication channels touched

**Comment by cmharlow** [comment]
First pass, need to add links.

Subject: Call for Reconciliation & Entity Resolution Use Cases / Needs / Stories

Hi all:

The LD4 Community Working Group on Reconciliation & Resolution is an open group working within the LD4L / LD4L Labs / LD4P broader family. A common theme we've experienced is trying to take our data and match concepts with other datasets - it is a big, messy problem with few (if any) common solutions across GLAM. As such, our Working Group is trying to pull together, analyze, find commonalities across GLAM, and propose some pragmatic solutions to needs around entity resolution and reconciliation in our data. You can see our group's charge, shared understandings, and work plan here if you'd like to learn more: ...

As part of this effort, we want to hear from you. If you're able, please take 10-15 minutes to share with us your needs around entity matching - whether it is taking string values and matching them to external authorities, having two entity identifiers that you need to determine if they're the same or not, capturing whether two ontologies' use of a class are not the same, or other. We want this to be as broad a collection of use cases, functional requirements, current services, or other needs and workflows for entity resolution and reconciliation with your data (and this is not limited to Linked Data!). You can share your needs with use by opening an issue on this Github repository, or if uncomfortable with using GitHub, emailing Arwen or Christina, this group's conveners.

The deadline for contributions is the end of this month (July), so we hope you'll take a moment sooner rather than later to add your needs. If you want to follow this group's work, including the analysis and output based on this collection, follow our GitHub repository here: 

Thank you for considering!

Best,
...

**Comment by ajs6f** [comment]
Looks pretty good to me-- just FYI @PilskS has put together a meeting on 12 July for lots of SI folks to discuss LD and potential use cases around reconciliation, so we will definitely bring some good stuff back from that.

**Comment by cmharlow** [comment]
@ajs6f rad, thanks for the review. I remembered you mentioning that - it's a rad idea, gonna try something similar with a few working groups at SUL - so no worries. We're aiming to finish collecting by the end of July.

**Comment by Conal-Tuohy** [comment]
Re communication channels, did you have a draft list of recipients, @cmh2166 ?

A few I can suggest:
- the Fedora (fcrepo) mail-lists (because of native RDF metadata) https://groups.google.com/forum/#!forum/fedora-community and https://groups.google.com/forum/#!forum/fedora-tech and maybe also any samvera and islandora groups?
- the international LODLAM list https://groups.google.com/forum/#!forum/lod-lam
- Europeana LOD https://groups.google.com/forum/#!forum/europeana-lod

**Comment by arwenhutt** [comment]
Looks really good @cmh2166 ! 
My only suggestion would be to write out "galleries, libraries, archives and museums" instead of using an acronym at it's first occurence, and probably delete _"across GLAM"_ in the sentence immediately following.  I think it'll be a bit more likely to feel inclusive to individuals or institutions working with less traditional collection materials - like research or scientific data sets.

**Comment by arwenhutt** [comment]
Oh, and for Samvera related lists:
* Samvera Community mail-lists  https://groups.google.com/forum/?hl=en#!forum/samvera-community
* Samvera Metadata list https://groups.google.com/forum/?hl=en#!forum/samvera-metadata

**Comment by cmharlow** [comment]
Can someone create a wiki page to store listservs? We can then reuse it and create columns per call/person who emailed. Thanks!

Christina Harlow

On Mon, Jul 10, 2017 at 6:53 PM arwenhutt

<
mailto:arwenhutt <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Oh, and for Samvera related lists:

Samvera Community mail-lists
https://groups.google.com/forum/?hl=en#!forum/samvera-community

Samvera Metadata listhttps://groups.google.com/forum/?hl=en#!forum/samvera-metadata

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/LD4P/ld4-community-recon/issues/43#issuecomment-314299961
, or

**Comment by arwenhutt** [comment]
@cmh2166 I drafted something along the lines you described: https://github.com/LD4P/ld4-community-recon/wiki/External-Communication-Channels 
wasn't sure where to put it, could have gone with "other communication channels" but that seemed to have a different focus.  Feel free to move, modify, etc. or let me know and I can move/modify!

**Comment by cmharlow** [comment]
Thanks a million, @arwenhutt ! I was in between leaving work after late meetings and trying to get some other stuff situated.

I'll try to update the text and get the github repo moved later this evening (blergh) so we can use the latest repo URL for the call.

**Comment by arwenhutt** [comment]
Updated text for call for use cases.  I expanded the GLAM acronym, added the link to our charge/about, and modified the sentence about the deadline being the end of July, because, well, that's tomorrow.  

---------
Subject: Call for Reconciliation & Entity Resolution Use Cases / Needs / Stories

Hi all:

The LD4 Community Working Group on Reconciliation & Resolution is an open group working within the LD4L / LD4L Labs / LD4P broader family. A common theme we've experienced is trying to take our data and match concepts with other datasets - it is a big, messy problem with few (if any) common solutions across galleries, libraries, archives and museums. As such, our Working Group is trying to pull together, analyze, find commonalities, and propose some pragmatic solutions to needs around entity resolution and reconciliation in our data. You can see our group's charge, shared understandings, and work plan here if you'd like to learn more: https://github.com/LD4/ld4-community-recon

As part of this effort, we want to hear from you. If you're able, please take 10-15 minutes to share with us your needs around entity matching - whether it is taking string values and matching them to external authorities, having two entity identifiers that you need to determine if they're the same or not, capturing whether two ontologies' use of a class are not the same, or other. We want this to be as broad a collection of use cases, functional requirements, current services, or other needs and workflows for entity resolution and reconciliation with your data (and this is not limited to Linked Data!). You can share your needs with use by opening an issue on this Github repository, or if uncomfortable with using GitHub, emailing Arwen or Christina, this group's conveners.

We'll begin reviewing use cases in the second half of August, so we hope you'll take a moment sooner rather than later to add your needs. If you want to follow this group's work, including the analysis and output based on this collection, follow our GitHub repository here:

Thank you for considering!

Best,
...

**Comment by cmharlow** [comment]
Cool. will add updated date + links in call tomorrow + queue folks for emailing out.
